OrdererOrgs:
  - Name: Example
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
    CA:
      Hostname: ca
      Key:
        Algo: ec
        Size: 256
      CSR:
        Hosts:
          - localhost
          - ca.example.com

PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    CA:
      Hostname: ca-org1
      Key:
        Algo: ec
        Size: 256
      CSR:
        Hosts:
          - localhost
          - ca-org1.org1.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: true
    CA:
      Hostname: ca-org2
      Key:
        Algo: ec
        Size: 256
      CSR:
        Hosts:
          - localhost
          - ca-org2.org2.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.example.com
    EnableNodeOUs: true
    CA:
      Hostname: ca-org3
      Key:
        Algo: ec
        Size: 256
      CSR:
        Hosts:
          - localhost
          - ca-org3.org3.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org4
    Domain: org4.example.com
    EnableNodeOUs: true
    CA:
      Hostname: ca-org4
      Key:
        Algo: ec
        Size: 256
      CSR:
        Hosts:
          - localhost
          - ca-org4.org4.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org5
    Domain: org5.example.com
    EnableNodeOUs: true
    CA:
      Hostname: ca-org5
      Key:
        Algo: ec
        Size: 256
      CSR:
        Hosts:
          - localhost
          - ca-org5.org5.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org6
    Domain: org6.example.com
    EnableNodeOUs: true
    CA:
      Hostname: ca-org6
      Key:
        Algo: ec
        Size: 256
      CSR:
        Hosts:
          - localhost
          - ca-org6.org6.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org7
    Domain: org7.example.com
    EnableNodeOUs: true
    CA:
      Hostname: ca-org7
      Key:
        Algo: ec
        Size: 256
      CSR:
        Hosts:
          - localhost
          - ca-org7.org7.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org8
    Domain: org8.example.com
    EnableNodeOUs: true
    CA:
      Hostname: ca-org8
      Key:
        Algo: ec
        Size: 256
      CSR:
        Hosts:
          - localhost
          - ca-org8.org8.example.com
    Template:
      Count: 1
    Users:
      Count: 1
