version: '3.8'

services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_FILELEDGER_LOCATION=/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls
      - ./channel-artifacts/system-genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - orderer-data:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - 6g-network

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7151
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7151
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=6g-network_6g-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
      - ./core-org1.yaml:/etc/hyperledger/fabric/core.yaml
      - peer0.org1.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 7151:7151
    networks:
      - 6g-network

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:8151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8151
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.example.com:8152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:8151
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=6g-network_6g-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls
      - ./core-org2.yaml:/etc/hyperledger/fabric/core.yaml
      - peer0.org2.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 8151:8151
    networks:
      - 6g-network

  peer0.org3.example.com:
    container_name: peer0.org3.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_ADDRESS=peer0.org3.example.com:9151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9151
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.example.com:9152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:9151
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=6g-network_6g-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/etc/hyperledger/fabric/tls
      - ./core-org3.yaml:/etc/hyperledger/fabric/core.yaml
      - peer0.org3.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 9151:9151
    networks:
      - 6g-network

  peer0.org4.example.com:
    container_name: peer0.org4.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.org4.example.com
      - CORE_PEER_ADDRESS=peer0.org4.example.com:10151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10151
      - CORE_PEER_CHAINCODEADDRESS=peer0.org4.example.com:10152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.example.com:10151
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=6g-network_6g-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls:/etc/hyperledger/fabric/tls
      - ./core-org4.yaml:/etc/hyperledger/fabric/core.yaml
      - peer0.org4.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 10151:10151
    networks:
      - 6g-network

  peer0.org5.example.com:
    container_name: peer0.org5.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.org5.example.com
      - CORE_PEER_ADDRESS=peer0.org5.example.com:11151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11151
      - CORE_PEER_CHAINCODEADDRESS=peer0.org5.example.com:11152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org5.example.com:11151
      - CORE_PEER_LOCALMSPID=Org5MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=6g-network_6g-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/tls:/etc/hyperledger/fabric/tls
      - ./core-org5.yaml:/etc/hyperledger/fabric/core.yaml
      - peer0.org5.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 11151:11151
    networks:
      - 6g-network

  peer0.org6.example.com:
    container_name: peer0.org6.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.org6.example.com
      - CORE_PEER_ADDRESS=peer0.org6.example.com:12151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12151
      - CORE_PEER_CHAINCODEADDRESS=peer0.org6.example.com:12152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org6.example.com:12151
      - CORE_PEER_LOCALMSPID=Org6MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=6g-network_6g-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/tls:/etc/hyperledger/fabric/tls
      - ./core-org6.yaml:/etc/hyperledger/fabric/core.yaml
      - peer0.org6.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 12151:12151
    networks:
      - 6g-network

  peer0.org7.example.com:
    container_name: peer0.org7.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.org7.example.com
      - CORE_PEER_ADDRESS=peer0.org7.example.com:13151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13151
      - CORE_PEER_CHAINCODEADDRESS=peer0.org7.example.com:13152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org7.example.com:13151
      - CORE_PEER_LOCALMSPID=Org7MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=6g-network_6g-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/tls:/etc/hyperledger/fabric/tls
      - ./core-org7.yaml:/etc/hyperledger/fabric/core.yaml
      - peer0.org7.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 13151:13151
    networks:
      - 6g-network

  peer0.org8.example.com:
    container_name: peer0.org8.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.org8.example.com
      - CORE_PEER_ADDRESS=peer0.org8.example.com:14151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14151
      - CORE_PEER_CHAINCODEADDRESS=peer0.org8.example.com:14152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org8.example.com:14151
      - CORE_PEER_LOCALMSPID=Org8MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=6g-network_6g-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/tls:/etc/hyperledger/fabric/tls
      - ./core-org8.yaml:/etc/hyperledger/fabric/core.yaml
      - peer0.org8.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 14151:14151
    networks:
      - 6g-network

volumes:
  orderer-data:
  peer0.org1.example.com:
  peer0.org2.example.com:
  peer0.org3.example.com:
  peer0.org4.example.com:
  peer0.org5.example.com:
  peer0.org6.example.com:
  peer0.org7.example.com:
  peer0.org8.example.com:

networks:
  6g-network:
    external: true
