version: '3.7'

networks:
  6g-network:
    name: config_6g-network

services:
  ca-orderer:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-orderer
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org1:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org1
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7154
    ports:
      - "7154:7154"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org2:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org2
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7254
    ports:
      - "7254:7254"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org3:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org3
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7354
    ports:
      - "7354:7354"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org4:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org4
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7454
    ports:
      - "7454:7454"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org5:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org5
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org5
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7554
    ports:
      - "7554:7554"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org6:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org6
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org6
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7654
    ports:
      - "7654:7654"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org7:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org7
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org7
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7754
    ports:
      - "7754:7754"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org8:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org8
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org8
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7854
    ports:
      - "7854:7854"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network
