version: '3.7'

networks:
  6g-network:
    name: config_6g-network

services:
  rca-orderer:
    image: hyperledger/fabric-ca:1.5.7
    container_name: rca-orderer
    environment:
      - FABRIC_CA_SERVER_CA_NAME=rca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    volumes:
      - ./crypto-config/ordererOrganizations/example.com/rca/ca-orderer.example.com-cert.pem:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - ./crypto-config/ordererOrganizations/example.com/rca/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - ./crypto-config/ordererOrganizations/example.com/rca/tls-msp/signcerts/cert.pem:/etc/hyperledger/fabric-ca-server/tls/tls-cert.pem
      - ./crypto-config/ordererOrganizations/example.com/rca/tls-msp/keystore/*_sk:/etc/hyperledger/fabric-ca-server/tls/tls-key.pem
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  rca-org1:
    image: hyperledger/fabric-ca:1.5.7
    container_name: rca-org1
    environment:
      - FABRIC_CA_SERVER_CA_NAME=rca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7154
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/rca/ca-org1.org1.example.com-cert.pem:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - ./crypto-config/peerOrganizations/org1.example.com/rca/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - ./crypto-config/peerOrganizations/org1.example.com/rca/tls-msp/signcerts/cert.pem:/etc/hyperledger/fabric-ca-server/tls/tls-cert.pem
      - ./crypto-config/peerOrganizations/org1.example.com/rca/tls-msp/keystore/*_sk:/etc/hyperledger/fabric-ca-server/tls/tls-key.pem
    ports:
      - "7154:7154"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  rca-org2:
    image: hyperledger/fabric-ca:1.5.7
    container_name: rca-org2
    environment:
      - FABRIC_CA_SERVER_CA_NAME=rca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7254
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/rca/ca-org2.org2.example.com-cert.pem:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - ./crypto-config/peerOrganizations/org2.example.com/rca/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - ./crypto-config/peerOrganizations/org2.example.com/rca/tls-msp/signcerts/cert.pem:/etc/hyperledger/fabric-ca-server/tls/tls-cert.pem
      - ./crypto-config/peerOrganizations/org2.example.com/rca/tls-msp/keystore/*_sk:/etc/hyperledger/fabric-ca-server/tls/tls-key.pem
    ports:
      - "7254:7254"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  rca-org3:
    image: hyperledger/fabric-ca:1.5.7
    container_name: rca-org3
    environment:
      - FABRIC_CA_SERVER_CA_NAME=rca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7354
    volumes:
      - ./crypto-config/peerOrganizations/org3.example.com/rca/ca-org3.org3.example.com-cert.pem:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - ./crypto-config/peerOrganizations/org3.example.com/rca/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - ./crypto-config/peerOrganizations/org3.example.com/rca/tls-msp/signcerts/cert.pem:/etc/hyperledger/fabric-ca-server/tls/tls-cert.pem
      - ./crypto-config/peerOrganizations/org3.example.com/rca/tls-msp/keystore/*_sk:/etc/hyperledger/fabric-ca-server/tls/tls-key.pem
    ports:
      - "7354:7354"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  rca-org4:
    image: hyperledger/fabric-ca:1.5.7
    container_name: rca-org4
    environment:
      - FABRIC_CA_SERVER_CA_NAME=rca-org4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7454
    volumes:
      - ./crypto-config/peerOrganizations/org4.example.com/rca/ca-org4.org4.example.com-cert.pem:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - ./crypto-config/peerOrganizations/org4.example.com/rca/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - ./crypto-config/peerOrganizations/org4.example.com/rca/tls-msp/signcerts/cert.pem:/etc/hyperledger/fabric-ca-server/tls/tls-cert.pem
      - ./crypto-config/peerOrganizations/org4.example.com/rca/tls-msp/keystore/*_sk:/etc/hyperledger/fabric-ca-server/tls/tls-key.pem
    ports:
      - "7454:7454"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  rca-org5:
    image: hyperledger/fabric-ca:1.5.7
    container_name: rca-org5
    environment:
      - FABRIC_CA_SERVER_CA_NAME=rca-org5
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7554
    volumes:
      - ./crypto-config/peerOrganizations/org5.example.com/rca/ca-org5.org5.example.com-cert.pem:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - ./crypto-config/peerOrganizations/org5.example.com/rca/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - ./crypto-config/peerOrganizations/org5.example.com/rca/tls-msp/signcerts/cert.pem:/etc/hyperledger/fabric-ca-server/tls/tls-cert.pem
      - ./crypto-config/peerOrganizations/org5.example.com/rca/tls-msp/keystore/*_sk:/etc/hyperledger/fabric-ca-server/tls/tls-key.pem
    ports:
      - "7554:7554"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  rca-org6:
    image: hyperledger/fabric-ca:1.5.7
    container_name: rca-org6
    environment:
      - FABRIC_CA_SERVER_CA_NAME=rca-org6
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7654
    volumes:
      - ./crypto-config/peerOrganizations/org6.example.com/rca/ca-org6.org6.example.com-cert.pem:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - ./crypto-config/peerOrganizations/org6.example.com/rca/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - ./crypto-config/peerOrganizations/org6.example.com/rca/tls-msp/signcerts/cert.pem:/etc/hyperledger/fabric-ca-server/tls/tls-cert.pem
      - ./crypto-config/peerOrganizations/org6.example.com/rca/tls-msp/keystore/*_sk:/etc/hyperledger/fabric-ca-server/tls/tls-key.pem
    ports:
      - "7654:7654"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  rca-org7:
    image: hyperledger/fabric-ca:1.5.7
    container_name: rca-org7
    environment:
      - FABRIC_CA_SERVER_CA_NAME=rca-org7
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7754
    volumes:
      - ./crypto-config/peerOrganizations/org7.example.com/rca/ca-org7.org7.example.com-cert.pem:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - ./crypto-config/peerOrganizations/org7.example.com/rca/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - ./crypto-config/peerOrganizations/org7.example.com/rca/tls-msp/signcerts/cert.pem:/etc/hyperledger/fabric-ca-server/tls/tls-cert.pem
      - ./crypto-config/peerOrganizations/org7.example.com/rca/tls-msp/keystore/*_sk:/etc/hyperledger/fabric-ca-server/tls/tls-key.pem
    ports:
      - "7754:7754"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  rca-org8:
    image: hyperledger/fabric-ca:1.5.7
    container_name: rca-org8
    environment:
      - FABRIC_CA_SERVER_CA_NAME=rca-org8
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7854
    volumes:
      - ./crypto-config/peerOrganizations/org8.example.com/rca/ca-org8.org8.example.com-cert.pem:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - ./crypto-config/peerOrganizations/org8.example.com/rca/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - ./crypto-config/peerOrganizations/org8.example.com/rca/tls-msp/signcerts/cert.pem:/etc/hyperledger/fabric-ca-server/tls/tls-cert.pem
      - ./crypto-config/peerOrganizations/org8.example.com/rca/tls-msp/keystore/*_sk:/etc/hyperledger/fabric-ca-server/tls/tls-key.pem
    ports:
      - "7854:7854"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network
