version: '3.7'

networks:
  6g-network:

services:
  ca-orderer:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-orderer
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls-key.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /root/6g-network/config/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt:/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - /root/6g-network/config/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key:/etc/hyperledger/fabric-ca-server/tls-key.pem
      - /root/6g-network/config/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - /root/6g-network/config/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/keystore/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - /root/6g-network/config/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/keystore/priv_sk/*_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org1:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org1
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls-key.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
      - FABRIC_CA_SERVER_PORT=7154
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17154
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /root/6g-network/config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt:/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key:/etc/hyperledger/fabric-ca-server/tls-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/keystore/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/keystore/priv_sk/*_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "7154:7154"
      - "17154:17154"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org2:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org2
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls-key.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
      - FABRIC_CA_SERVER_PORT=7254
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /root/6g-network/config/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.crt:/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.key:/etc/hyperledger/fabric-ca-server/tls-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/keystore/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/keystore/priv_sk/*_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "7254:7254"
      - "18054:18054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org3:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org3
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls-key.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
      - FABRIC_CA_SERVER_PORT=7354
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19054
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /root/6g-network/config/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.crt:/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.key:/etc/hyperledger/fabric-ca-server/tls-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp/keystore/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp/keystore/priv_sk/*_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "7354:7354"
      - "19054:19054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org4:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls-key.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
      - FABRIC_CA_SERVER_PORT=7454
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:20054
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /root/6g-network/config/crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls/server.crt:/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls/server.key:/etc/hyperledger/fabric-ca-server/tls-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls/ca.crt:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/msp/keystore/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/msp/keystore/priv_sk/*_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "7454:7454"
      - "20054:20054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org5:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org5
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls-key.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
      - FABRIC_CA_SERVER_PORT=7554
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:21054
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /root/6g-network/config/crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/tls/server.crt:/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/tls/server.key:/etc/hyperledger/fabric-ca-server/tls-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/tls/ca.crt:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/msp/keystore/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/msp/keystore/priv_sk/*_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "7554:7554"
      - "21054:21054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org6:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org6
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls-key.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
      - FABRIC_CA_SERVER_PORT=7654
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:22054
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /root/6g-network/config/crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/tls/server.crt:/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/tls/server.key:/etc/hyperledger/fabric-ca-server/tls-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/tls/ca.crt:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/msp/keystore/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/msp/keystore/priv_sk/*_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "7654:7654"
      - "22054:22054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org7:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org7
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls-key.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
      - FABRIC_CA_SERVER_PORT=7754
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:23054
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /root/6g-network/config/crypto-config/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/tls/server.crt:/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/tls/server.key:/etc/hyperledger/fabric-ca-server/tls-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/tls/ca.crt:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/msp/keystore/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/msp/keystore/priv_sk/*_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "7754:7754"
      - "23054:23054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network

  ca-org8:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca-org8
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org8
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls-key.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
      - FABRIC_CA_SERVER_PORT=7854
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:24054
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - /root/6g-network/config/crypto-config/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/tls/server.crt:/etc/hyperledger/fabric-ca-server/tls-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/tls/server.key:/etc/hyperledger/fabric-ca-server/tls-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/tls/ca.crt:/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/msp/keystore/priv_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
      - /root/6g-network/config/crypto-config/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/msp/keystore/priv_sk/*_sk:/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "7854:7854"
      - "24054:24054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - 6g-network
