General:
  ListenAddress: 0.0.0.0
  ListenPort: 7050
  TLS:
    Enabled: true
    PrivateKey: /var/hyperledger/orderer/tls/server.key
    Certificate: /var/hyperledger/orderer/tls/server.crt
    RootCAs:
      - /var/hyperledger/orderer/bundled-tls-ca.pem
    ClientAuthRequired: false
  BootstrapMethod: file
  BootstrapFile: /etc/hyperledger/fabric/genesis.block
  LocalMSPDir: /var/hyperledger/orderer/msp
  LocalMSPID: OrdererMSP
  BCCSP:
    Default: SW

FileLedger:
  Location: /var/hyperledger/production/orderer

Operations:
  ListenAddress: 0.0.0.0:8443
  TLS:
    Enabled: false

Metrics:
  Provider: disabled
